### PR TITLE
kenzo: add libuiblur blob

### PR DESCRIPTION
**Pull request by TheScarastic**

### CODE REVIEW

**Comment by TheStrix** [comment]
@akhilnarang it ain't working on kenzo surprisingly :/

**Comment by akhilnarang** [comment]
:+1:

**Comment by dadi11** [comment]
did you add <bool name="config_ui_blur_enabled">true</bool> in overlay/frameworks/base/core/res/res/values/config.xml ?

**Comment by TheScarastic** [comment]
yeah we did it review.cyanogenmod.org/#/c/155345/2/overlay/frameworks/base/core/res/res/values/config.xml

**Comment by dadi11** [comment]
well, I missed it. another idea is maybe try system/vendor/lib instead lib64.. ;)

**Comment by TheStrix** [comment]
Don't work

**Pull request closed without merging**
