### PR TITLE
scorpio: Update blobs to 8.1.4

### PR DESCRIPTION
**Pull request by PsyMan47**

### CODE REVIEW

**Comment by luca020400** [comment]
You have to update the modem assert in the device tree

**Comment by luk1337** [comment]
you use hangouts?

**Comment by PsyMan47** [comment]
Already updated the modem timestamp. Can i send the pull request to android_device_xiaomi_scorpio too? No hangouts, only telegram @Uomo_Psichedelico

**Comment by luk1337** [comment]
Ehh no telegram...

**Comment by luk1337** [comment]
And we don't accept pull requests on devices fyi.

**Pull request merged**
