### PR TITLE
Add Vulkan and Bullhead Widevine along with VoLTE

### PR DESCRIPTION
**Pull request by minz1**
I'm the original author of the Vulkan commits...

### CODE REVIEW

**Comment by poad42** [comment]
Wait Extracting libs from a ROM package gives you authorship OK?

**Comment by dadi11** [comment]
@poad42 kanging his commits doesn't make you an author more than him..

**Comment by poad42** [comment]
Hold on, I never kanged them I extracted them from the leaked ROM package of hydrogen from xda. Just so that you know.

**Comment by bgcngm** [comment]
Big mess up here. Closing this.

**Comment by dadi11** [comment]
@poad42 I saw your PR's commits before you edit them

**Comment by minz1** [comment]
@poad42 i honestly wouldn't care if you didn't pretend as if the commits were yours

**Comment by poad42** [comment]
Hey dude, I am just surprised that you are claiming authorship for the blobs that you simply extracted and couldn't even bother to create a new branch for pushing the commits. Next time if you derp something use git commit -a --amend or use git rebase sha1~1 -i to clean up don't split a single commit into 4 and make a mess. And seriously volte blobs? and remove unnecessary devices?

**Pull request closed without merging**
